### ISSUE TITLE
Experiencing various issues with snapshots not updating correctly.

### ISSUE THREAD

**Issue by lichie567** [enthh/FeralSnapshots#1] opened 2023-01-29 05:28 UTC
Recently I have been experiencing issues with this addon, especially with Rake snapshots not updating correctly.

These are the incorrect behaviors that I've identified:

1. If I have a Rake applied with both Tiger's Fury and a Sudden Ambush proc, the snapshot does not update when my Tiger's Fury buff falls off.
2. If I apply a Rake with Sudden Ambush and then soon after get another Sudden Ambush proc and use that proc on Shred, the addon updates the snapshot as if my current Rake has somehow become stronger (aka my next rake would be relatively weaker) which is not possible or correct.
3. Sometimes when I apply a Rake with a Sudden Ambush proc, the snapshot will incorrectly show 100 (indicating my next rake would be equal value) when it should be showing 62 (i.e. currently applied Rake is 60% stronger than next Rake).

**Comment by lichie567** [comment] 2023-01-29 05:29
Here is the Rake weakaura that I am using:

`!WA:2!1zvxVTrwz41ycfgqABdOOUPrvEZUBuYIWQXLKkvHq4jXojDDJnJT3Mci8CMzo2ZHmEodNZzsI7D1sSQa35Rrvul29kUk)cwL)a8klu)bKFc5wUH3ZzSBsHeFXKZhVF8CE)45n5QoF)5dMp4vFYyMppUjpv4tx6deNuVBxjv9J(oIbzRoyU1F0dkUXPKy)qUObNfR82QY(TQ4mXNZJc4hh38ywc19SzBRe0JgARTQ7qLG1RhvilUIy6Y3ksL09j9PHNlt9OhrJvnt72LDYPD2QCZwDA2QStlbAM6XrdCDmc4TlLePcDIr1KwxGgOYjeFvZeAu0EbUJiPcI5UfTDihshkZUqA9ox0qqrx40SrLA1otlUrewGCrV13yJhvQKTAqc1rFtj70yMYtre9OQXbupeDTWlf7w25PvBxBuA80NI1kG1BHfHLsMhHuhINKlmq9P8aQlAHi0Zl40pnsXw5UZ9F(y37(9U33664hrKsNTDAV32WhEwlJyf(Iy8npuBhT7DhPxze0fwYljImGkm3Ia331w)DUX69zEj88lrGX7W9f7wPwdeVqbno)QZ8tLkE)MkI)HYes30yFfJhV6AwfWFcQkvexOprfwSBeNlwTkvqIAgtsKHCLSOdnIOyhr1X3vBJiChe9RUCwuA51wROIJiPWNxy9h8G1SOXbWIEzEmlbit(zT3FVwDk32P8JZEopot5cnQv(5vC6G59DQ0QZw7wE)DQS9Pzk3rNw8KkIkv64hs9pe(qy9K1VE4RXvLtysL8sKPXILLfCFOiSeSguybu)sxV(XC1nAJK7GvCyaOvwUxhK)NFWfy3avetI(sSghn3lV4qknPSo7OCW4fpCKKg1101aZHfts8HiikA4ySY0H2d1r(KfGfNGB9Wmtpbpno4v3lzEf9evhzib7OoiRtm3iZz6pl)zjj3(ksSfpIlEsUC5YFE2PZCQD52TQN8JnhssXakck)NXcuH2LXTxyUa7mObMdF5KS28Np1JNzU)pGPcw3b4dqGjzfTfEO9(13VssH3HOoD5c04Ds6Oy9PD6Zd6OFNUjRDtIemaBzz(DuHckwJff8dhBKY38wYJ)GffyyrF40Wrg4MgooipslLCV)FZxC9PlTJ5X0rtVlwLC7Qc2lk8Rtjbi0ifA1k5JVjWLiO(mDgn)7LjMfxs(0BsXiApI)GoMEi3jgboMlcEMGKm8ztxm5DqYWRuVDRA7HbZBFL3Oj5ncVr3yuVrwE4ierErym9(3K3Z2L7sh0K9c6hn59IB5s(ORr9SfoARe8QLGF11jLC6cWbkp6ZEyrPHlbSnfEWwW2qfOkSZlVMYIzcFPf2nhShmh8e4lGAUWthG8O1Hgh8DFqXsBa7NL)BcTapWh(YCWZcHdGNd)g43c)ouTo5GFVl4EhGKdAN)Tt6fXpUQG(htPX(dAGvgLS1hfEgslUt00gKWH6Z0XCNgyjF0y92A04EQWFWP61ZsVJ6ntLRuhQpZi1bxvQM(i)BEJ)BfY8pmMkL5n3uJHRVJXh2yINkc9cPSEHQ1TJ4KGV5Cd7oMVdmC6l4jzX9IO)ly5fGpXc(u93ZNY4hfDOE8qOzQqmsOkchLCusg3Vf8t1YMne69nQRTGhrTSLyzGwMXcdLJoeaFFpCcDxwplbXqfk30bZrc1cJc4DYyFDTziBOLxx8pYqRHZMWJtCJzAQeE8MWWQyQZ5mkrsBQeMO5TMeOz5WRn83cjfDvGCOwgJVDS7tyXgfHxDl4pd)f4VIl)t)VNK8tM5snNZ2mjbR)dCTFbN3p3yf3)OmE37M7R(6LzbNQNovy1TQxB71CUKh50Uc8Foabh21N)ISMHQ6J0yXR5wovQSVdjkjKKVukAL2k(Xo8nJD2qkyXAxqdDowZpUUjiV1umHZaC0CCJ1VoMjg(4vGnRcw5xMNm)Vy4rebtJ4ZPNKWYciTWgmNJirP0spS4Mc)qsCpQ8ZxbE9tYLpx(HjcogWWO2TXsUILkEjLikIl8g9CJI)8I6QQmxDl4V5L1BP95VeEDjCcm83xCMfH3KzQhEftT5mnH)HbOWRHV2lIfFigBNQAEDl9BGV5uwCwllIDRj4iem2vpX8wTMx6SbA3hn)r)7d(Vd`

**Comment by lichie567** [comment] 2023-01-29 05:51
Actually I think the addon is also thinking that Moment of Clarity also works for Rake, and the snapshot is sometimes changing when I get an MoC proc.

**Comment by enthh** [comment] 2023-01-29 11:44
Thanks for reporting!

> If I have a Rake applied with both Tiger's Fury and a Sudden Ambush proc, the snapshot does not update when my Tiger's Fury buff falls off.

Could this relate to the addon not calculating Raging Fury's extension of Tiger's Fury in v10.0.5.1? Did you have Raging Fury talented and were casting finishers and noticed the next rake would be of lower damage while still having TIger's Fury up towards the end of its duration?

Related: https://www.curseforge.com/wow/addons/feralsnapshots?comment=5

> If I apply a Rake with Sudden Ambush and then soon after get another Sudden Ambush proc and use that proc on Shred, the addon updates the snapshot as if my current Rake has somehow become stronger (aka my next rake would be relatively weaker) which is not possible or correct.

I haven't tested this case and it indeed sounds like a bug in the way the addon handles buff expiration on spell casting. I'll investigate a fix.

>  Sometimes when I apply a Rake with a Sudden Ambush proc, the snapshot will incorrectly show 100 (indicating my next rake would be equal value) when it should be showing 62 (i.e. currently applied Rake is 60% stronger than next Rake).

Were you inside an Incarnation: Avatar of Ashamane/Berserk buff window? If so, the behavior is correct, that both Sudden Ambush and Berserk cause Rake and Shred to deal damage as though you were stealthed.

**Comment by enthh** [comment] 2023-01-29 16:07
> If I apply a Rake with Sudden Ambush and then soon after get another Sudden Ambush proc and use that proc on Shred, the addon updates the snapshot as if my current Rake has somehow become stronger (aka my next rake would be relatively weaker) which is not possible or correct.

I'm not able to reproduce this. Could you also try adding an event UNIT_PLAYER_POWER:player to trigger 3 of your weakaura to see if the weakaura is a frame ahead or behind the combat log event handler of the addon?

This actually sounds like it's correct behavior where the sequence of events are:

```
Proc sudden ambush
Rake (x1.6)
Remove sudden ambush (x1.0)
Rake Relative = 63%

Proc sudden ambush (x1.6)
Rake Relative = 100%

Shred
Remove sudden ambush (x1.0)
Rake Relative = 63%
```

It could be that a target swap on a mob that had a double clawed rake with sudden ambush should show that rake to be snapshotted at x1.6 damage.

Another interaction could be the rake was applied with Ashmane's Guidance show up as having the same stealth modifier as sudden ambush.

It'd be great if you could give me a sequence of casts and buffs do so I can reproduce this.

**Comment by enthh** [comment] 2023-03-22 17:20
Closing because I am unable to reproduce this after the Tiger's Fury refresh on finisher change.

**Closed as completed by enthh** 2023-03-22 17:20 UTC
